### ISSUE TITLE
Error Cannot use 'in' operator to search for 'providers' in undefined In [SplitButton]

### ISSUE THREAD

**Issue by abalad** [TemainfoSistemas/truly-ui#67]
`ERROR in TypeError: Cannot use 'in' operator to search for 'providers' in undefined
    at D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:111:70
    at Array.filter (native)
    at _extractLazyRoutesFromStaticModule (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:111:29)
    at D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\Labs\Truly-UI\Maicon\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\Labs\Truly-UI\Maicon\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
`

**Comment by abalad** [comment]
I found the problem with the index (barrel):

**Before**
`import { ButtonModule } from '../button';`

**After**
`import { ButtonModule } from '../button/index';`  <-------------------- HERE 

Adding index to module import fixed problem
